inherit_from:
  - .rubocop_todo.yml

Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 99

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false